/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_bsu_JVmipcl_MIP */

#ifndef _Included_by_bsu_JVmipcl_MIP
#define _Included_by_bsu_JVmipcl_MIP
#ifdef __cplusplus
extern "C" {
#endif
#undef by_bsu_JVmipcl_MIP_INF
#define by_bsu_JVmipcl_MIP_INF 1.0E20
#undef by_bsu_JVmipcl_MIP_VAR_INF
#define by_bsu_JVmipcl_MIP_VAR_INF 1.0E12
#undef by_bsu_JVmipcl_MIP_VAR_INT
#define by_bsu_JVmipcl_MIP_VAR_INT 4096L
#undef by_bsu_JVmipcl_MIP_VAR_BIN
#define by_bsu_JVmipcl_MIP_VAR_BIN 8192L
/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    createCMIP
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_by_bsu_JVmipcl_MIP_createCMIP
  (JNIEnv *, jobject, jstring);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    openMatrix
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_MIP_openMatrix
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    closeMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_MIP_closeMatrix
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    setVarPriority
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_MIP_setVarPriority
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    setAutoCutPattern
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_MIP_setAutoCutPattern
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    optimize
 * Signature: (JDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_MIP_optimize__JDLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jdouble, jstring);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    optimize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_MIP_optimize__
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    isSolution
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_by_bsu_JVmipcl_MIP_isSolution
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    isSolutionOptimal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_by_bsu_JVmipcl_MIP_isSolutionOptimal
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    isInfeasible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_by_bsu_JVmipcl_MIP_isInfeasible
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    timeLimitStop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_by_bsu_JVmipcl_MIP_timeLimitStop
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    getObjVal
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_by_bsu_JVmipcl_MIP_getObjVal
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    getSolution
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_MIP_getSolution
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    printSolution
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_MIP_printSolution
  (JNIEnv *, jobject, jstring);

/*
 * Class:     by_bsu_JVmipcl_MIP
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_MIP_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
