/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_bsu_JVmipcl_LP */

#ifndef _Included_by_bsu_JVmipcl_LP
#define _Included_by_bsu_JVmipcl_LP
#ifdef __cplusplus
extern "C" {
#endif
#undef by_bsu_JVmipcl_LP_INF
#define by_bsu_JVmipcl_LP_INF 1.0E20
#undef by_bsu_JVmipcl_LP_VAR_INF
#define by_bsu_JVmipcl_LP_VAR_INF 1.0E12
/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    createLP
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_by_bsu_JVmipcl_LP_createLP
  (JNIEnv *, jobject, jstring);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    openMatrix
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_LP_openMatrix
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    closeMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_LP_closeMatrix
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    addVar
 * Signature: (IIDDD)I
 */
JNIEXPORT jint JNICALL Java_by_bsu_JVmipcl_LP_addVar
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jdouble);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    addColumn
 * Signature: (IIDDD[D[IZ)I
 */
JNIEXPORT jint JNICALL Java_by_bsu_JVmipcl_LP_addColumn
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jdouble, jdoubleArray, jintArray, jboolean);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    addCtr
 * Signature: (IIDD)I
 */
JNIEXPORT jint JNICALL Java_by_bsu_JVmipcl_LP_addCtr
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    addRow
 * Signature: (IIDD[D[IZ)I
 */
JNIEXPORT jint JNICALL Java_by_bsu_JVmipcl_LP_addRow
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jdoubleArray, jintArray, jboolean);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    addEntry
 * Signature: (DII)V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_LP_addEntry
  (JNIEnv *, jobject, jdouble, jint, jint);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    setObjCoeff
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_LP_setObjCoeff
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    setObjSense
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_LP_setObjSense
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    beSilent
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_LP_beSilent
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    preprocOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_LP_preprocOff
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    optimize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_LP_optimize
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    isSolution
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_by_bsu_JVmipcl_LP_isSolution
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    isLpInfeasible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_by_bsu_JVmipcl_LP_isLpInfeasible
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    isLpUnbounded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_by_bsu_JVmipcl_LP_isLpUnbounded
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    getObjVal
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_by_bsu_JVmipcl_LP_getObjVal
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    getSolution
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_LP_getSolution
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    getInconsistencyCertificate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_LP_getInconsistencyCertificate
  (JNIEnv *, jobject);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    printSolution
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_LP_printSolution
  (JNIEnv *, jobject, jstring);

/*
 * Class:     by_bsu_JVmipcl_LP
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_bsu_JVmipcl_LP_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
